language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - android-27

script:
  - ./gradlew clean build

after_success:
  - ./gradlew bintrayUpload